// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaxIr7O2L-12jGyxhhkLokD8Vvvza0XcU',
    appId: '1:760505590984:web:16e648c2c83fa7a5ba71fd',
    messagingSenderId: '760505590984',
    projectId: 'learndna-ai1',
    authDomain: 'learndna-ai1.firebaseapp.com',
    storageBucket: 'learndna-ai1.firebasestorage.app',
    measurementId: 'G-SN9S2Y0N0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaNTW6vvmXSEYnrfFodIQglcSEYffBlzo',
    appId: '1:760505590984:android:461e14bc3a32ca48ba71fd',
    messagingSenderId: '760505590984',
    projectId: 'learndna-ai1',
    storageBucket: 'learndna-ai1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg1m0jICgP9GP9aM4ryGfNYoUvrsTNg0o',
    appId: '1:760505590984:ios:cdb506fc8a1b9257ba71fd',
    messagingSenderId: '760505590984',
    projectId: 'learndna-ai1',
    storageBucket: 'learndna-ai1.firebasestorage.app',
    iosBundleId: 'com.example.learndnaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg1m0jICgP9GP9aM4ryGfNYoUvrsTNg0o',
    appId: '1:760505590984:ios:cdb506fc8a1b9257ba71fd',
    messagingSenderId: '760505590984',
    projectId: 'learndna-ai1',
    storageBucket: 'learndna-ai1.firebasestorage.app',
    iosBundleId: 'com.example.learndnaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaxIr7O2L-12jGyxhhkLokD8Vvvza0XcU',
    appId: '1:760505590984:web:16e648c2c83fa7a5ba71fd',
    messagingSenderId: '760505590984',
    projectId: 'learndna-ai1',
    authDomain: 'learndna-ai1.firebaseapp.com',
    storageBucket: 'learndna-ai1.firebasestorage.app',
    measurementId: 'G-SN9S2Y0N0V',
  );

}